export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'; 
export const LOG_OUT = 'LOG_OUT';
export const LOAD_HOME_SUCCESS = 'LOAD_HOME_SUCCESS';
export const CREATE_HOME_SUCCESS = 'CREATE_HOME_SUCCESS';
export const DELETE_HOME_SUCCESS = 'DELETE_HOME_SUCCESS';
export const LOAD_SENSOR_SUCCESS = 'LOAD_SENSOR_SUCCESS';
